### ISSUE TITLE
fix: scrollstate is kept at navigation

### ISSUE THREAD

**Issue by PatrickMi** [maevsi/maevsi#904] opened 2022-11-11 19:28 UTC
In the nuxt 3 version of maevsi the scrollstate is used in the event that is opened which leads to the user seeing the lower part of the page although he should see the page from the beginning.

**Comment by dargmuesli** [comment] 2023-04-11 02:20
Is this still an issue? I cannot reproduce it.

**Comment by dargmuesli** [comment] 2023-05-10 05:50
Closing this due lack of reproduction instructions. Feel free to reopen if the issue is still existing!

**Closed by dargmuesli** 2023-05-10 05:50 UTC
Labels: bug
